---
title: "Response time correction of Contros HydroC pCO~2~ data"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r packages}
library(tidyverse)
library(seacarb)
library(data.table)
library(broom)
library(lubridate)
library(tibbletime)
```

# Load RTs

```{r apply_residual_thresholds_for_tau}

tau_df <- read_csv(here::here("data/_summarized_data_files", "Tina_V_HydroC_response_times_all.csv"))

max_Zero_ID <- max(unique(tau_df[tau_df$date_time < ymd_hms("2018-07-17;13:08:34"),]$Zero_ID))

tau_df <- tau_df %>% 
  mutate(pump_power = if_else(Zero_ID <= max_Zero_ID, "1W", "8W"))


# define subsetting parameters
resid_limit <- 1

# subset determined tau values by residual threshold
tau_resid <- tau_df %>% 
  group_by(Zero_ID) %>% 
  mutate(resid_max = max(resid, na.rm = TRUE)) %>% 
  filter(resid_max < resid_limit) %>% 
  select(-resid_max) %>% 
  ungroup()

tau_resid <- tau_resid %>% 
  filter(Zero_ID != 2)

```


# fit response times as a function of water temperature:

```{r linear_model_response_time}

RT_fit <- tau_resid %>% 
  group_by(pump_power) %>% 
  do(fit = lm(tau ~ tem, data = .)) %>% 
  tidy(fit) %>% 
  select(pump_power, term, estimate) %>% 
  spread(term, estimate)

RT_fit

rm(list=setdiff(ls(), c("tau_resid", "RT_mean", "RT_fit")))

```


# Response time correction data preparation

```{r response_correction_data_preparation}

df <- read_csv(here::here("data/_merged_data_files",
                          "BloomSail_CTD_HydroC.csv"),
               col_types = cols(ID = col_character(),
                                pCO2_analog = col_double(),
                                pCO2 = col_double(),
                                Zero = col_factor(),
                                Flush = col_factor(),
                                Zero_ID = col_integer(),
                                deployment = col_integer(),
                                duration = col_double(),
                                mixing = col_character()))

# extract relevant parts

df <- df %>%
  select(date_time, ID, type, station, dep, sal, tem, Zero, Flush, pCO2, deployment, Zero_ID)

df <- df %>% 
  filter(type == "P")

df <- df %>%
  group_by(ID, station) %>% 
  mutate(duration = as.numeric(date_time - min(date_time)),
         pump_power = if_else(date_time < ymd_hms("2018-07-17;13:08:34"), "1W", "8W")) %>%
  arrange(date_time)

```


```{r include_profile_meta_data}
# Load profile meta data 

meta <- read_csv(here::here("Data/_summarized_data_files",
                          "Tina_V_Sensor_meta.csv"),
                 col_types = cols(ID = col_character()))


# Merge data and meta information 

df <- full_join(df, meta)
rm(meta)


# creating descriptive variables ------------------------------------------
df <- df %>% 
  mutate(phase = "standby",
         phase = if_else(duration >= start & duration < down & !is.na(down) & !is.na(start),   "down", phase),
         phase = if_else(duration >= down  & duration < lift & !is.na(lift) & !is.na(down ),   "low",  phase),
         phase = if_else(duration >= lift  & duration < up   & !is.na(up  ) & !is.na(lift  ),  "mid",  phase),
         phase = if_else(duration >= up    & duration < end  & !is.na(end ) & !is.na(up   ),   "up",   phase))

df <- df %>% 
  select(-c(start, down, lift, up, end, comment))

df <- df %>% 
  filter(Zero == 0, Flush == 0)


```

# Reponse time correction

```{r RT_correction}

# Response time correction approach after Bittig --------------------------

RT_corr <- function(c1, c0, dt, tau) {
  ( 1 / ( 2* (( 1+(2*tau/dt) )^(-1) ))) * (c1 - (1-(2* (( 1+(2*tau/dt) )^(-1) ))) * c0)
}


# Assign T-dependent response time (tau) values ----------------------------------------------

RT_fit <- RT_fit %>% 
  rename(tau_intercept = `(Intercept)`, tau_slope=tem)

df_fit <- full_join(df, RT_fit)

df_fit <- df_fit %>% 
  mutate(tau = tau_intercept + tau_slope *tem,
         RT = "T-dependent") %>% 
  select(-tau_intercept, -tau_slope)

df_fit <- df_fit %>% 
  mutate(RT = "T-dependent")


# Merge data sets with constand and T-dependent tau

df <-df_fit

rm(df_fit)


# Prepare data set for RT correction --------------------------------------

df <- df %>% 
  group_by(RT) %>% 
  arrange(date_time) %>% 
  mutate(dt = as.numeric(as.character(date_time - lag(date_time)))) %>% 
  ungroup()

# measurement frequency

freq <- df %>% 
  filter(dt < 13) %>% 
  group_by(ID) %>% 
  summarise(dt_mean = round(mean(dt, na.rm = TRUE),0))

df <- full_join(df, freq)

# tau factors

df <- expand_grid(df, tau_factor = seq(0.8, 1.6, 0.02))

df <- df %>%
  mutate(tau_test = tau*tau_factor)


# Apply RT correction to entire data set

for(i_ID in unique(df$ID)){
  
#i_ID <- "180716"
  
  freq_sub <- freq %>% filter(ID == i_ID) %>% pull(dt_mean)
  
  window <- 30 / freq_sub
  rolling_mean   <- rollify(~mean(.x, na.rm = TRUE), window = window)

  df_sub <- df %>%
    filter(ID == i_ID) %>% 
    group_by(station, RT, tau_factor) %>% 
    mutate(pCO2_RT = RT_corr(pCO2, lag(pCO2), dt, tau_test),
           pCO2_RT = if_else(pCO2_RT %in% c(Inf, -Inf), NaN, pCO2_RT),
           window = window,
           pCO2_RT_mean = rolling_mean(pCO2_RT)
           #pCO2_RT_median = rolling_median(pCO2_RT)
           ) %>% 
    ungroup()
  
  # time shift RT corrected data
  shift <- as.integer(as.character(window/2))
  
  df_sub <- df_sub %>%
    group_by(station, RT, tau_factor) %>% 
    mutate(pCO2_RT_mean = lead(pCO2_RT_mean, shift)) %>% 
    ungroup()
  
  
  if (exists("df_corr")){df_corr <- bind_rows(df_corr, df_sub)}
  else{df_corr <- df_sub}
  
  rm(df_sub, freq_sub, rolling_mean, shift, window)
  
}

df <- df_corr
rm(RT_corr, i_ID, freq, df_corr)

df %>% 
 write_csv(here::here("data/_merged_data_files",
                      "_BloomSail_CTD_HydroC_profiles_RT_highres_taufactor.csv"))
rm(df)

```

# Diagnosis and conclusion


```{r read_highres_RT_data}

df <-
 read_csv(here::here("data/_merged_data_files",
                      "X_BloomSail_CTD_HydroC_profiles_RT_highres_taufactor.csv"),
               col_types = cols(ID = col_character(),
                                pCO2 = col_double(),
                                Zero = col_factor(),
                                Flush = col_factor(),
                                p_type = col_factor(),
                                Zero_ID = col_integer(),
                                deployment = col_integer(),
                                duration = col_double()))

```

```{r compute_pCO2_offset_profiles}

# pCO2 offset up - down cast

RT_diff <- df %>% 
  filter(phase %in% c("down", "up")) %>% 
  mutate(dep_int = as.numeric(as.character( cut(dep, seq(0,40,1), seq(0.5,39.5,1)))),
         tau_factor = as.factor(tau_factor)) %>% 
  select  (ID, station, RT, tau_factor, p_type, dep_int, phase, pCO2, pCO2_RT_mean) %>% 
  group_by(ID, station, RT, tau_factor, p_type, dep_int, phase) %>%
  summarise_all("mean", na.rm = TRUE) %>% 
  ungroup() %>% 
  pivot_longer(cols = c(pCO2, pCO2_RT_mean), names_to = "correction") %>% 
  pivot_wider(names_from = phase, values_from = value) %>% 
  mutate(d_pCO2 = up - down,
         mean_pCO2 = (down + up)/2,
         d_pCO2_rel = 100 * d_pCO2 / mean_pCO2)


RT_diff %>% 
 write_csv(here::here("data/_merged_data_files",
                      "X_BloomSail_CTD_HydroC_profiles_RT_cast-offset_highres_taufactor.csv"))

```

```{r read_offset_datasets}


RT_diff <-
 read_csv(here::here("data/_merged_data_files",
                      "X_BloomSail_CTD_HydroC_profiles_RT_cast-offset_highres_taufactor.csv"),
               col_types = cols(ID = col_character()))

df_equi_int <- 
 read_csv(here::here("data/_merged_data_files",
                      "BloomSail_CTD_HydroC_reference_pCO2_int.csv"),
               col_types = cols(ID = col_character()))


```

### Downcast vs reference value

```{r compute_pCO2_offset_reference_value}

equi_diff <- full_join(RT_diff, df_equi_int) %>% 
  filter(!is.na(pCO2_equi)) %>% 
  mutate(d_pCO2_equi = down - pCO2_equi,
         d_pCO2_equi_rel = 100 * d_pCO2_equi / pCO2_equi)

equi_diff %>% 
 write_csv(here::here("data/_merged_data_files",
                      "X_BloomSail_CTD_HydroC_profiles_RT_reference-offset_highres_taufactor.csv"))

```

## Summary metrics

```{r calculate_performance_metrics}

# select upper 20 m water depth with no more than 2 depth intervals missing during Down AND Upcast

RT_diff_20 <- RT_diff %>% 
  filter(dep_int <= 20) %>% 
  group_by(ID, station, RT, tau_factor, correction) %>% 
  filter(sum(is.na(d_pCO2)) <= 2) %>% 
  ungroup()

RT_diff_sum_profile <- RT_diff_20 %>% 
  mutate(d_pCO2_abs = abs(d_pCO2),
         d_pCO2_rel_abs = abs(d_pCO2_rel)) %>% 
  group_by(RT, tau_factor, dep_int, correction) %>% 
  summarise(mean = mean(d_pCO2, na.rm = TRUE),
            mean_abs = mean(d_pCO2_abs, na.rm = TRUE),
            mean_rel = mean(d_pCO2_rel, na.rm = TRUE),
            mean_rel_abs = mean(d_pCO2_rel_abs, na.rm = TRUE)) %>% 
  ungroup() %>% 
  pivot_longer(cols = 5:8, names_to = "estimate", values_to = "dpCO2")

RT_diff_sum_mean <- RT_diff_sum_profile %>% 
  filter(dep_int < 20) %>% 
  group_by(RT, estimate, correction, tau_factor) %>% 
  summarise(mean_dpCO2 = mean(dpCO2)) %>% 
  ungroup()
  
equi_diff_sum <- equi_diff %>% 
    mutate(d_pCO2_equi_abs = abs (d_pCO2_equi),
           d_pCO2_equi_rel_abs = abs(d_pCO2_equi_rel)) %>% 
  group_by(correction, RT, tau_factor) %>% 
  summarise(mean = mean(d_pCO2_equi, na.rm = TRUE),
            mean_abs = mean(d_pCO2_equi_abs, na.rm = TRUE),
            mean_rel = mean(d_pCO2_equi_rel, na.rm = TRUE),
            mean_rel_abs = mean(d_pCO2_equi_rel_abs, na.rm = TRUE)) %>% 
  ungroup()



RT_diff_sum_mean %>%
 write_csv(here::here("data/_merged_data_files",
                      "X_BloomSail_CTD_HydroC_profiles_RT_cast-offset_highres_taufactor_mean.csv"))

equi_diff_sum %>%
 write_csv(here::here("data/_merged_data_files",
                      "X_BloomSail_CTD_HydroC_profiles_RT_reference-offset_highres_taufactor_mean.csv"))

```


```{r tau_optimum_reference_pCO2, fig.cap="Mean pCO2 offset from reference values as a function of the factor applied to tau."}

equi_diff_sum %>%
  ggplot(aes(tau_factor, mean_abs, col=RT, shape=correction, linetype=correction))+
  geom_hline(yintercept = 0)+
  geom_point()+
  labs(y = "Mean delta pCO2 from reference [µatm]")

equi_diff_sum %>%
  filter(correction == "pCO2_RT_mean") %>% 
  slice(which.min(mean_abs))

```

```{r plot_cast_delta_pCO2}

RT_diff_sum_profile %>% 
  filter(correction == "pCO2_RT_mean") %>% 
  ggplot()+
  geom_path(aes(dpCO2, dep_int, col=as.factor(tau_factor)))+
  scale_y_reverse()+
  coord_cartesian(xlim = c(-30,30))+
  geom_vline(xintercept = 0)+
  theme_bw()+
  geom_hline(yintercept = 20)+
  geom_vline(xintercept = 0)+
  geom_vline(xintercept = c(-10,10), col="red")+
  facet_grid(estimate~RT)

```

```{r tau_optimum_cast_delta_pCO2}

RT_diff_sum_mean %>% 
  ggplot(aes(tau_factor, mean_dpCO2, col=RT))+
  geom_point()+
  geom_hline(yintercept = 0)+
  facet_grid(correction~estimate)+
  theme_bw()


RT_diff_sum_mean %>%
  filter(correction == "pCO2_RT_mean", estimate == "mean_abs") %>% 
  slice(which.min(mean_dpCO2))

RT_diff_sum_mean %>%
  filter(correction == "pCO2_RT_mean", estimate == "mean_rel_abs") %>% 
  slice(which.min(mean_dpCO2))

```

