---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

On this website, you find code and explanations to quantify the net community production (NCP) during a cyanobacteria bloom in the Baltic Sea through vertically resolved pCO~2~ measurements.

The outcome of this study was submitted to the Copernicus Journal **Biogeosciences** where it is handled as: bg-2021-40

Please navigate trough the navbar on top to take a look at the various chapters of this project.

The links in the upper right corner direct you to the source code of this project stored in a Github repository; and to Jens' main homepage.

The data set required to re-run the analysis is not included in the Github repository, but a copy of copy of the code together with all relevant data sets is available through Zenodo.org under doi: [10.5281/zenodo.4553314](https://doi.org/10.5281/zenodo.4553314){target="_blank"}

Dr. Jens Daniel Müller, `r format(Sys.time(), '%Y')`
