---
title: "MLD"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---


```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r packages}
library(tidyverse)
library(seacarb)
library(oce)
library(marelac)
```

# Sensor data

1m gridded, downcast profiles were used.

```{r read_Tina-V_Sensor_data}

df <-
  read_csv(here::here("Data/_merged_data_files", "BloomSail_CTD_HydroC_CT.csv"))

```


# Mixed layer depth

```{r calulcate_seawater_density}

df <- df %>% 
  mutate(rho = swSigma(salinity = sal, temperature = tem, pressure = dep/10))

 # seacarb = rho(S = sal, T = tem, P = pres),
 # marelac = sw_dens(S = sal, t = tem, p = pres + 1, method = "Gibbs")

```

```{r calculate_MLD}
# density criterion

df <- expand_grid(df, rho_lim = c(0.1,0.2,0.5))

df <- df %>% 
  group_by(ID, date_time_ID, station, rho_lim) %>% 
  mutate(d_rho = rho - min(rho)) %>% 
  mutate(layer = if_else(d_rho > rho_lim, "deep", "surface")) %>% 
  ungroup()
  
MLD <- df  %>% 
  group_by(ID, date_time_ID, station, rho_lim) %>% 
  filter(d_rho > rho_lim) %>% 
  summarise(MLD = min(dep)) %>% 
  ungroup()

df <- full_join(df, MLD)

```


```{r plot_density_profiles, fig.cap="Overview density profiles at stations (P01-P14) and cruise dates (ID). Horizontal lines indicate determined MLD", fig.asp = 1.5, eval=FALSE}

df %>% 
  filter(dep < 30) %>% 
  arrange(dep) %>% 
  ggplot(aes(rho, dep))+
  geom_hline(aes(yintercept = MLD))+
  geom_path()+
  geom_point(aes(col=layer))+
  scale_y_reverse()+
  scale_color_brewer(palette = "Set1", direction = -1)+
  facet_grid(ID~station)

```



```{r plot_MLD_timeseries}

MLD_sum <- MLD %>% 
  select(-station) %>% 
  group_by(ID, date_time_ID, rho_lim)%>%
  summarise_all(list(~mean(.),~sd(.),~min(.), ~max(.)))

MLD_sum %>% 
  ggplot()+
  geom_ribbon(aes(date_time_ID, ymin = min, ymax = max), alpha = 0.5)+
  geom_path(aes(date_time_ID, mean))+
  geom_errorbar(aes(date_time_ID, ymin = mean-sd, ymax = mean+sd))+
  geom_point(aes(date_time_ID, mean))+
  labs(x="Mean transect date", y="Mixed layer depth [m]")+
  ylim(0,30)+
  facet_wrap(~rho_lim)

```

Rho, S, and T profiles were plotted individually 
[pdf here](https://github.com/jens-daniel-mueller/BloomSail/tree/master/output/Plots/MLD/profiles_MLD_individual.pdf){target="_blank"}.

```{r plot_profiles_MLD_individual, eval=FALSE}

df_long <- df %>% 
  pivot_longer(cols = c("sal", "tem", "rho"), names_to = "parameter", values_to = "value")

pdf(file=here::here("output/Plots/MLD",
    "profiles_MLD_individual.pdf"), onefile = TRUE, width = 9, height = 5)

for(i_ID in unique(df_long$ID)){
  for(i_station in unique(df_long$station)){
 
      
      #i_ID      <-      unique(df_long$ID)[1]
      #i_station <- unique(df_long$station)[1]

      if (nrow(df_long %>% filter(ID == i_ID, station == i_station)) > 0){
      
    
    
      print(
    
        
        df_long %>%
          arrange(date_time) %>% 
          filter(ID == i_ID,
                 station == i_station,
                 dep<20) %>%
          ggplot(aes(value,dep))+
          geom_hline(aes(yintercept = MLD))+
          geom_path()+
          scale_y_reverse()+
          scale_color_brewer(palette = "Set1")+
          labs(y="Depth [m]", title = str_c(i_ID," | ",i_station))+
          facet_wrap(~parameter, scales = "free_x")+
          theme_bw()
      )
    }
  }
}

dev.off()

rm(i_ID, i_station)



```


# NCP penetration depth

```{r NCP_penetration_depth}

CT_ts <-
  read_csv(here::here("Data/_merged_data_files", "BloomSail_CTD_HydroC_CT_cumulative_timeseries.csv"))

CT_profiles <-
  read_csv(here::here("Data/_merged_data_files", "BloomSail_CTD_HydroC_CT_cumulative_profiles.csv"))

CT_conc_surf <-
  CT_profiles %>% 
  filter(dep < 3,
         parameter == "CT",
         sign == "neg") %>% 
  group_by(ID, date_time_ID) %>% 
  summarise(dCT = mean(diff_value))

CT_conc_surf %>% 
  ggplot(aes(date_time_ID, dCT))+
  geom_path()

NCP_integ <- CT_ts %>% 
  filter(sign == "neg") %>% 
  group_by(ID, date_time_ID) %>% 
  summarise(dNCPi = sum(dCT))

NCP_integ %>% 
  ggplot(aes(date_time_ID, dNCPi))+
  geom_path()

CT <- full_join(CT_conc_surf, NCP_integ)

CT <- CT %>% 
  mutate(dep_NCP = -(dNCPi/dCT)*1e3)

CT_long <- CT %>% 
  pivot_longer(3:5, names_to = "parameter", values_to = "values")

CT_long %>% 
  ggplot(aes(date_time_ID, values))+
  geom_path()+
  geom_point()+
  facet_grid(parameter~., scales = "free_y")

```

