---
title: "Nomenclature used in this project"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

Throughout this analysis, the following naming conventions for objects
(data sets) and variables are used.

# Nomenclature of objects and data sets

The following names should be identical for stored files and objects in
R environment

-   source

    -   tx: data recorded on SV Tina V, where x stands for:

        -   s: Sea-Bird SBE 16 sensor
        -   h: Contros HydroC CO2 sensor
        -   t: track data (coordinates + timestamp)
        -   m: ts + th + tt merged (variables within tm are interpolated
            to a common time stamp)
        -   b: discrete bottle samples

    -   fm: data recorded on SOOP Finnmaid

    -   og: data recorded on Ostergarnsholm ICOS flux tower

    -   gt: GETM (high-res huydographical model)

    -   mp: bathymetric map

-   subsetting and modification levels

    -   profiles vs surface: operation mode SV Tina V
    -   ID: mean values for cruise (reduced temporal resolution)
    -   daily: daily mean values
    -   long: data stored in long format (all observations in only 2
        columns "var" and "value")
    -   fix: constant, unique values such as long-term means, starting
        dates, etc
    -   iCT: includes cumulative numbers as iCT estimates
    -   NCP: includes cumulative numbers as NCP estimates
    -   CT_tem: data subset to analyse changes of CT with tem
    -   3d vs 2d: surface vs depth resolved GETM data

# Nomenclature of variables

-   Descriptive variables

    -   date
    -   date_time
    -   date_time_ID: mean date of cruise
    -   date_time_ID_diff: time differences in between cruises
    -   date_time_ID_ref: mean date in between cruises corresponding to
        observed incremental changes
    -   station
    -   ID: character identifying starting date of cruise as YYMMDD
    -   dep: 1m depth intervals
    -   lat
    -   lon
    -   deployment
    -   Zero: Zeroing period of HydroC Sensor
    -   Flush: Period following zero, reading recovers to ambient value
    -   mixing: Two phases of the Flush period

-   Observed variables: column names, or identifier in column "var" for
    long-format tables

    -   pCO2: partial pressure of carbon dioxide, with following postfix
        indicating manipulation level

        -   \_analog: analog HydroC signal recorded on SeaBird CTD
        -   \_raw: HydroC signal recorded internally
        -   \_corr: pCO2_raw postprocessed by manufacturer
        -   \_equi: pCO2_corr at the end of an in-water equilibration
            period at constant depth
        -   \_RT: Response time corrected pCO2_corr
        -   \_RT_mean: running mean of pCO2_RT
        -   none: pCO2_RT_mean gridded to regular depth levels

    -   sal

    -   tem

    -   nCT: CT normalized to AT, or calculated from pCO2, temperature,
        and fixed AT, S (please note that this variable is referred to
        as C~T~\* in the accompanying manuscript)

    -   CT: Measured dissolved inorganic carbon

    -   AT: Measured total alkalinity

    -   U10: wind speed at 10m

    -   mld: mixed or mixing layer depth

-   Variable name extension

    -   mean: mean value
    -   sd: standard deviation
    -   min: min value
    -   max: max value
    -   int: interpolated value
    -   grid: value gridded to a coarser resolution
    -   diff: difference to previous value
    -   diff_daily: difference to previous value divided by number of
        days
    -   delta: offset from an alternative estimate of the same parameter
    -   i: intergrated over depth
    -   cum: cumulative value over time
    -   sign: identifier for pos. or neg. differences
    -   rel: relative to some absolute value

-   p_XXX: ggplot object

# Code chunk labelling

-   read\_: read data
-   calc\_: perform calculations, mutate variables, etc
-   chunks for plotting are labeled according to plot content, because
    name controls plot file name

# ToD0

Github repo Explain subsetting of deployments Explain metadata creation

CT dynamics Map data preparation in read-in file

Reconstruction fm + gt in read_in und merging section implement exact
subsetting coordinated for getm data
